server:
  port: 8080

# token??
token:
  # ???????
  header: Authorization
  # ????
  secret: abcdefghijklmnopqrstuvwxyz
  # ????????30???
  expireTime: 30

# MyBatis??
mybatis:
  # ???????
  typeAliasesPackage: com.coderitl.**.domain
  # ??mapper?????????mapper.xml????
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # ?????????
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper????
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# flowable???
flowable:
  # true ????????????????????????????(???????)
  database-schema-update: true
  # ??????JOB
  async-executor-activate: false

# ?????
# druid ?????
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/coderitl?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useServerPrepStmts=true
      username: root
      password: root
      initial-size: 1
      min-idle: 1
      max-active: 20
