server:
  port: 8080

# token??
token:
  # ???????
  header: Authorization
  # ????
  secret: abcdefghijklmnopqrstuvwxyz
  # ????????30???
  expireTime: 30

# MyBatis??
mybatis:
  # ???????
  typeAliasesPackage: com.coderitl.**.domain
  # ??mapper?????????mapper.xml????
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # ?????????
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper????
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# flowable???
flowable:
  # true ????????????????????????????(???????)
  database-schema-update: true
  # ??????JOB
  async-executor-activate: false